FROM node:20-slim AS builder
WORKDIR /app

COPY package.json yarn.lock tsconfig.json ./
RUN yarn install --frozen-lockfile --production
COPY src/app/bff src/app/bff

FROM node:20-slim AS runner
WORKDIR /app

COPY --from=builder /app /app
COPY --from=builder /app/node_modules /app/node_modules

CMD ["yarn", "fastify"]
