version: "3.8"
services:
  nextjs:
    build:
      context: ../../ # ✅ 루트 디렉토리를 컨텍스트로 설정
      dockerfile: src/app/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - fastify
    env_file:
      - ../../.env # ✅ 루트 디렉토리에 있는 .env 파일 사용

  fastify:
    build:
      context: ../../ # ✅ 루트 디렉토리를 컨텍스트로 설정
      dockerfile: src/app/bff/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../../.env # ✅ 루트 디렉토리에 있는 .env 파일 사용
